# Copyright (c) Visly Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

version: 2
jobs:
  android:
    docker:
      - image: circleci/android:api-28
    
    environment:
      _JAVA_OPTIONS: "-Xmx1500m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

    steps:
      - checkout
      - run: yes | sdkmanager --licenses || true
      - run: sdkmanager --update || true
      - run: cd android && ./gradlew androidDependencies --no-daemon --max-workers 2
      - run: cd android && ./gradlew test --no-daemon --max-workers 2

  ios:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      - run: cd ios && xcodebuild test -workspace Example/ShardKit.xcworkspace -scheme ShardKit -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0'

  core:
    docker:
      - image: rust:1

    steps:
      - checkout

      - restore_cache:
          key: target-cache

      - run: rustc --version; cargo --version; rustup --version
      - run: rustup component add rustfmt
      - run: cd core && cargo fmt -- --check
      - run: cd core && cargo test
      - run: cd core/android && cargo build
      - run: cd core/ios && cargo build

      - save_cache:
          key: target-cache
          paths:
            - ~/.cargo
            - ./target

workflows:
  version: 2
  test_all:
    jobs:
      - android
      - ios
      - core
