platform :ios, '12.0'
use_frameworks!

target 'ShardKit_Example' do
  pod 'ShardKit', :path => '../../'

  pod 'SnapKit', '~> 4.2.0'
  pod 'Alamofire', '~> 4.8'
  pod 'AppCenter', '~> 1.12'

  target 'ShardKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end